apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: rundeck
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: rundeck
      name: rundeck
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: rundeck:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: rundeck
        git:
          uri: 	http://cd_user@192.168.56.31:7990/scm/opendevstack/ods-core.git
          ref: master
        sourceSecret:
          name: cd-user-token
        type: Git
      strategy:
        dockerStrategy: {}
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers: []
